name: CI/CD: Docker Compose Deploy to VPC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHAAVI }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Prepare remote server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            set -e
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt update
              sudo apt install -y docker.io docker-compose
              sudo systemctl enable docker
              sudo systemctl start docker
            fi
            mkdir -p ~/on-air
            cd ~/on-air
            rm -rf *
          EOF

      - name: Copy project files to server
        run: |
          scp -i ~/.ssh/id_ed25519 -r . ${{ secrets.USER }}@${{ secrets.HOST }}:~/on-air

      - name: Run Docker Compose
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USER }}@${{ secrets.HERO }} << 'EOF'
            cd ~/on-air
            docker compose down || true
            docker compose up -d --build
          EOF
