name: CI/CD using Docker Hub and SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_WORD }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Build and push Docker image with Docker Compose
        run: |
          docker build -t ${{ secrets.DOCKER_NAME }}/portfolio:latest .
          docker push ${{ secrets.DOCKER_NAME }}/portfolio:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHAAVI }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            docker network inspect nw-njl >/dev/null 2>&1 || \
              docker network create \
                --subnet=172.29.0.0/16 \
                --driver=bridge nw-njl

            docker pull ${{ secrets.DOCKER_NAME }}/portfolio:latest

            docker stop folio-njl || true
            docker rm foloio-njl || true

            docker run -d --name folio-njl \
              --network nw-njl \
              --ip 172.29.0.2 \
              ${{ secrets.DOCKER_NAME }}/portfolio:latest
          EOF
